SELECT * FROM TRUE9_PREPAID_SUBSCRIBER  WHERE  hbp_subscriber_no = 2571; --SUB_ACTV_LOCATION 

-- pre
SELECT * FROM TRUE9_PREPAID_SUBSCRIBER 
WHERE prim_resource_tp = 'C'
AND prim_resource_val IN (
'0658107286'
)
AND sub_status = 'A' ;

-- PP SOC
SELECT HBP_SUBSCRIBER_NO, SOC, SOC_SEQ_NO, EFFECTIVE_DATE, EXPIRATION_DATE, SOC_STS_RSN_CD 
FROM TRUE9_SERVICE_AGREEMENT
WHERE HBP_SUBSCRIBER_NO = '70529574';

-- post
SELECT s.subscriber_no,s.SYS_CREATION_DATE ,s.SYS_UPDATE_DATE ,prim_resource_val,sub_status ,CALC_PYM_CATEGORY ,SUB_STATUS_DATE 
FROM subscriber s,agreement_resource ar 
WHERE s.subscriber_no = ar.agreement_no 
AND resource_value = '0834018191' 
ORDER BY SYS_CREATION_DATE DESC;

-- CCBS act pre post msisdn
SELECT * FROM (
SELECT HBP_SUBSCRIBER_NO,PRIM_RESOURCE_VAL,SUB_STATUS,CALC_PYM_CATEGORY 
FROM TRUE9_PREPAID_SUBSCRIBER 
WHERE PRIM_RESOURCE_TP = 'C' 
AND PRIM_RESOURCE_VAL = '0909496136'
--AND SUB_STATUS in ('A','S') 
UNION ALL 
SELECT SUBSCRIBER_NO,resource_value,SUB_STATUS,CALC_PYM_CATEGORY 
FROM subscriber s,agreement_resource ar 
WHERE s.subscriber_no = ar.agreement_no 
--AND prim_res_param_cd = 'MSISDN' 
AND resource_value = '0909496136' 
AND ar.expiration_date IS NULL
--AND SUB_STATUS in ('A','S','D','U') 
);

-- SIM CCBS act pre post
SELECT 'PRE' ACT_CAT,c.prim_resource_val ctn,c.expiration_date ctn_exp_date,s.prim_resource_val sim,s.expiration_date sim_exp_date
FROM true9_prepaid_resource s,true9_prepaid_resource c
WHERE s.hbp_subscriber_no = c.hbp_subscriber_no
AND s.prim_resource_val = '896600081791522880'
AND s.prim_resource_tp = 'S'
AND s.expiration_date IS NULL
AND c.prim_resource_tp = 'C'
AND c.expiration_date IS NULL
UNION ALL
SELECT 'POS' ACT_CAT, ar2.resource_value ctn ,ar2.expiration_date ctn_exp_date, ar1.resource_value,ar1.expiration_date sim_exp_date 
FROM agreement_resource ar1,agreement_resource ar2 WHERE ar1.agreement_no  = ar2.agreement_no 
AND ar1.resource_type = 'S'
AND ar1.resource_value = '896600081791522880'
AND ar1.expiration_date IS NULL
AND ar2.resource_type = 'C'
AND ar2.expiration_date IS NULL  ;

-- #####################################################
CREATE TABLE TEMP_CM_ACTIVE_MSISDN NOLOGGING AS
SELECT /*+PARALLEL(PRE, 8) FULL(PRE) */ prim_resource_val resource_value, '1' CM_TYPE 
FROM PRDAPPO.TRUE9_PREPAID_SUBSCRIBER PRE
WHERE PRE.PRIM_RESOURCE_TP = 'C' AND PRE.EXPIRATION_DATE IS NULL
UNION
SELECT /*+PARALLEL(POST, 8) FULL(POST) */ resource_value, '2' CM_TYPE
FROM AGREEMENT_RESOURCE POST
WHERE POST.RESOURCE_TYPE = 'C'
AND POST.EXPIRATION_DATE IS NULL;

-- #####################################################
SELECT /*+FULL(CM) PARALLEL(CM, 4) */ 
NAS.RESOURCE_VALUE, NAS_ZONE_DESC, ACT_TYPE, NAS_POOL, 
CASE CM_TYPE WHEN '1' THEN 'PRE' ELSE 'POST' END CM_TYPE
FROM TEMP_NASNUM NAS 
LEFT JOIN TEMP_CM_ACTIVE_MSISDN CM ON CM.resource_value = NAS.resource_value
WHERE CM.RESOURCE_VALUE IS NOT NULL
ORDER BY CM.CM_TYPE, NAS.RESOURCE_VALUE;
-- #####################################################


SELECT c.PRIM_RESOURCE_VAL CTN,c.expiration_date CTN_EXP_DATE,s.PRIM_RESOURCE_VAL SIM,s.expiration_date SIM_EXP_DATE 
FROM TRUE9_PREPAID_RESOURCE c, TRUE9_PREPAID_RESOURCE s 
WHERE c.hbp_subscriber_no = s.hbp_subscriber_no
AND c.PRIM_RESOURCE_TP = 'C'
AND s.PRIM_RESOURCE_TP = 'S'
AND s.PRIM_RESOURCE_VAL = '896600401191320079'
AND s.expiration_date IS NULL ;


SELECT * FROM TRUE9_PREPAID_RESOURCE
WHERE HBP_SUBSCRIBER_NO IN (
SELECT HBP_SUBSCRIBER_NO FROM TRUE9_PREPAID_SUBSCRIBER 
WHERE prim_resource_tp = 'C'
AND prim_resource_val = '0966871808')
ORDER BY SYS_CREATION_DATE DESC;

SELECT * FROM TRUE9_PREPAID_SUBSCRIBER
WHERE prim_resource_tp = 'C'
AND prim_resource_val IN (
'0966871808'
) AND sub_status = 'A';

SELECT * FROM TRUE9_PREPAID_RESOURCE
WHERE HBP_SUBSCRIBER_NO = '65190532';

SELECT HBP_SUBSCRIBER_NO, SOC, SOC_SEQ_NO, EFFECTIVE_DATE, EXPIRATION_DATE, SOC_STS_RSN_CD 
FROM TRUE9_SERVICE_AGREEMENT
WHERE HBP_SUBSCRIBER_NO IN (
SELECT HBP_SUBSCRIBER_NO
FROM TRUE9_PREPAID_SUBSCRIBER 
WHERE prim_resource_tp = 'C'
AND prim_resource_val = '0966871808')
ORDER BY SYS_CREATION_DATE DESC;

SELECT HBP_SUBSCRIBER_NO, SOC, SOC_SEQ_NO, EFFECTIVE_DATE, EXPIRATION_DATE, SOC_STS_RSN_CD 
FROM TRUE9_SERVICE_AGREEMENT
WHERE HBP_SUBSCRIBER_NO IN (
SELECT HBP_SUBSCRIBER_NO
FROM TRUE9_PREPAID_SUBSCRIBER
WHERE PRIM_RESOURCE_VAL = '0966871808') 
ORDER BY SYS_CREATION_DATE DESC;

--=========================================

SELECT HBP_SUBSCRIBER_NO,PRIM_RESOURCE_VAL,SUB_STATUS,CALC_PYM_CATEGORY 
FROM TRUE9_PREPAID_SUBSCRIBER 
WHERE PRIM_RESOURCE_TP = 'C' 
AND PRIM_RESOURCE_VAL = '0966871808';

SELECT /*+ FULL(s) PARALLEL (s,64) */ HBP_SUBSCRIBER_NO,prim_resource_val,SUB_STATUS ,EFFECTIVE_DATE
FROM TRUE9_PREPAID_SUBSCRIBER s 
WHERE prim_resource_val = '0967816492'
AND PRIM_RESOURCE_TP = 'C' 
AND sub_status = 'A';

SELECT PRIM_RESOURCE_TP,PRIM_RESOURCE_VAL 
FROM TRUE9_PREPAID_RESOURCE
WHERE HBP_SUBSCRIBER_NO = '65190530';

-- PP SOC
SELECT HBP_SUBSCRIBER_NO, SOC, SOC_SEQ_NO, EFFECTIVE_DATE, EXPIRATION_DATE, SOC_STS_RSN_CD 
FROM TRUE9_SERVICE_AGREEMENT
WHERE HBP_SUBSCRIBER_NO = '65190521';

SELECT SOC_CD ,SOC_NAME ,SOC_DESCRIPTION 
,TO_CHAR(SYS_CREATION_DATE ,'dd/mm/yyyy') SYS_CREATION_DATE 
FROM CSM_OFFER
WHERE SOC_CD IN ('10327710','10104810','710318','710428')

--==============================================
                 
SELECT * FROM TRUE9_PREPAID_SUB_HIS

SELECT * FROM TRUE9_PREPAID_RES_HIS

SELECT * FROM TRUE9_SERVICE_AGREEMENT

SELECT * FROM TRUE9_ADDRESS_NAME_LINK

SELECT * FROM TRUE9_NAME_DATA

SELECT * FROM TRUE9_ADDRESS_DATA

SELECT * FROM TRUE9_SERVICE_AGREEMENT

SELECT * FROM TRUE9_ADR_NM_LINK_HIS

TRUE9_NAME_HIS
TRUE9_ADDRESS_HIS
TRUE9_SERVICE_AGR_HIS
TRUE9_SERVICE_AGR_PARM
TRUE9_SVC_AGR_PARAM_HIS

