SELECT * FROM OMX_FILE_SUMMARY 
WHERE file_name LIKE '%CCP%20161215%'
ORDER BY file_name ASC 


/* File preact */
SELECT * FROM OMX_FILE_SUMMARY 
WHERE file_id = '04-5173a3c9-fddd-48e2-909b-f34f03e4d107' 
ORDER BY  file_timestamp DESC

-- CCP MSISDN
SELECT * FROM OMX_APP.V_ORDERS 
WHERE msisdn IN (
'0640045432'
)
AND order_type = '56' 
AND channel IN ('CCP')

SELECT TRUNC(FILE_DATE) FILE_DEACT_DATE, COUNT(*) FROM ASRM_MAIN_CREDIT
WHERE TRUNC(FILE_DATE) BETWEEN TRUNC(SYSDATE-7) AND TRUNC(SYSDATE)
GROUP BY FILE_DATE
ORDER BY FILE_DATE DESC

SELECT * FROM ASRM_MAIN_CREDIT
WHERE msisdn = '0961625156'
ORDER BY FILE_DATE DESC
