SELECT RESOURCE_VALUE, RESOURCE_POOL_ID, RESOURCE_STATUS, LAST_ACTIVITY_NAME, LAST_ACTIVITY_DATE, RESOURCE_PARENT_VALUE 
FROM rm1_resource_history
WHERE resource_value = '0965155132' 
AND LAST_ACTIVITY_NAME = 'RELEASE'
ORDER BY LAST_ACTIVITY_DATE DESC

SELECT RESOURCE_VALUE,RESOURCE_STATUS, LAST_ACTIVITY_NAME,sys_creation_date,USER_ID --18746
FROM rm1_resource_history WHERE resource_value = '0965155132' AND RESOURCE_STATUS = 'AGING' 
AND sys_creation_date =  (SELECT MAX(sys_creation_date) FROM rm1_resource_history WHERE resource_value = '0965155132' AND RESOURCE_STATUS = 'AGING') 