-- check report
SELECT UR_NUMBER,TRUNC(a.SYS_CREATION_DATE) DATE1,UR_NO,PAIR_REQUEST_DATE DATE2
FROM ASRM_PARPACT_REPORT_STS a,ASRM_PAIR_TRACKING b
WHERE TRUNC(PAIR_REQUEST_DATE) > SYSDATE-10
AND TRUNC(a.SYS_CREATION_DATE) > SYSDATE-10
ORDER BY TRUNC(a.SYS_CREATION_DATE) DESC,TRUNC(PAIR_REQUEST_DATE) DESC;

SELECT *
FROM ASRM_PAIR_TRACKING 
--WHERE UR_NO = 'UR170101021'
--ORDER BY TRUNC(PAIR_REQUEST_DATE) DESC
ORDER BY UR_NO DESC;

DELETE FROM ASRM_PAIR_TRACKING 
WHERE UR_NO IN (
'UR170701239',
'UR170701240',
'UR170701241',
'UR170701242',
'UR170701243',
'UR170701244',
'UR170701245'
);
--AND ORDER_QUANTITY ='1' UR161001941 UR161001753

SELECT TRUNC(UR_ORDER_DATE),UR_NO,TRUNC(PAIR_REQUEST_DATE)
FROM ASRM_PAIR_TRACKING 
--WHERE PAIR_REQUEST_DATE > TO_DATE(SYSDATE-1,'dd/mm/yyyy')
--WHERE ROWNUM < 5
ORDER BY TRUNC(PAIR_REQUEST_DATE) DESC;

DELETE FROM ASRM_PAIR_TRACKING ;

SELECT *
FROM ASRM_PAIR_TRACKING 
WHERE PAIR_REQUEST_DATE > TO_DATE('01/02/2016','dd/mm/yyyy')
ORDER BY TRUNC(PAIR_REQUEST_DATE) DESC;

--mon
SELECT TO_CHAR(TO_DATE(TRUNC(PAIR_REQUEST_DATE)),'MM-YY') AS MONTH , 
COMPANY ,SUM(ORDER_QUANTITY) AS SUMMARY 
FROM ASRM_PAIR_TRACKING 
GROUP BY TO_CHAR(TO_DATE(TRUNC(PAIR_REQUEST_DATE)),'MM-YY'),COMPANY 
ORDER BY TO_CHAR(TO_DATE(TRUNC(PAIR_REQUEST_DATE)),'MM-YY') DESC ;

--mon
SELECT TO_CHAR(TO_DATE(TRUNC(PAIR_REQUEST_DATE)),'MM-YY') AS MONTH 
FROM ASRM_PAIR_TRACKING 
GROUP BY TO_CHAR(TO_DATE(TRUNC(PAIR_REQUEST_DATE)),'MM-YY') 
ORDER BY TO_CHAR(TO_DATE(TRUNC(PAIR_REQUEST_DATE)),'MM-YY') DESC ;

--Week
SELECT TO_CHAR(TO_DATE(TRUNC(PAIR_REQUEST_DATE)),'MM-YY') Week , 
TO_CHAR(TO_DATE(PAIR_REQUEST_DATE),'DD-MM-YYYY') Pair,COMPANY,SUM(ORDER_QUANTITY) AS SUMMARY
FROM ASRM_PAIR_TRACKING  
WHERE TRUNC(PAIR_REQUEST_DATE) BETWEEN TRUNC(SYSDATE-7) AND TRUNC(SYSDATE-1)
GROUP BY PAIR_REQUEST_DATE,COMPANY 
ORDER BY PAIR_REQUEST_DATE DESC;

--week
SELECT TO_CHAR(TO_DATE(PAIR_REQUEST_DATE),'DD-MM-YYYY') Pair 
FROM ASRM_PAIR_TRACKING 
WHERE TRUNC(PAIR_REQUEST_DATE) BETWEEN TRUNC(SYSDATE-7) AND TRUNC(SYSDATE-1)
GROUP BY PAIR_REQUEST_DATE 
ORDER BY PAIR_REQUEST_DATE DESC

--sum week
SELECT TO_CHAR(TO_DATE(TRUNC(PAIR_REQUEST_DATE)),'W') Week,TRUNC(PAIR_REQUEST_DATE) pair,COMPANY,SUM(ORDER_QUANTITY) AS SUMMARY
FROM ASRM_PAIR_TRACKING  
WHERE TRUNC(PAIR_REQUEST_DATE) = TRUNC(SYSDATE-8) 
GROUP BY TO_CHAR(TO_DATE(TRUNC(PAIR_REQUEST_DATE)),'W'),TRUNC(PAIR_REQUEST_DATE),COMPANY
ORDER BY TRUNC(PAIR_REQUEST_DATE) DESC


INSERT INTO ASRM_PAIR_TRACKING 
(COMPANY, UR_ORDER_DATE, UR_NO, UR_DESC, ORDER_QUANTITY, PAIR_REQUEST_DATE, REMARK, SYS_CREATION_DATE)
VALUES
('RMV', TO_DATE('28-Feb-17', 'DD-MM-YY','NLS_DATE_LANGUAGE = American'), 'UR170209999', 'Pair Preact SIM 3G', '180000', TO_DATE('17-Feb-16', 'DD-MM-YY','NLS_DATE_LANGUAGE = American'), 'กาก', TO_DATE(SYSDATE))

DELETE FROM ASRM_PAIR_TRACKING 
WHERE UR_NO = 'UR170209999'

-- edit 
ALTER TABLE ASRM_PAIR_TRACKING  RENAME COLUMN SYA_CREATION_DATE TO SYS_CREATION_DATE;

-- UPDATE
UPDATE ASRM_PAIR_TRACKING SET 
COMPANY = 'RMV'
WHERE UR_NO = ''

SELECT * FROM ASRM_PAIR_TRACKING 
WHERE COMPANY <> 'RMV'
AND COMPANY <> 'RFT'


------==================================================================================================================------------------------

SELECT UR_NUMBER,TRUNC(a.SYS_CREATION_DATE) DATE1,UR_NO,PAIR_REQUEST_DATE DATE2
FROM ASRM_PARPACT_REPORT_STS a,ASRM_PAIR_TRACKING b
WHERE TRUNC(PAIR_REQUEST_DATE) > SYSDATE-20
AND TRUNC(a.SYS_CREATION_DATE) > SYSDATE-20
ORDER BY TRUNC(a.SYS_CREATION_DATE) DESC,TRUNC(PAIR_REQUEST_DATE) DESC;

-- O
SELECT * FROM ASRM_PARPACT_REPORT_STS 
--WHERE UR_NUMBER = 'UR170501733' 
ORDER BY UR_NUMBER DESC;--TRUNC(SYS_CREATION_DATE) DESC


UPDATE ASRM_PARPACT_REPORT_STS 
SET PAIR_PREACT_DATE = SYSDATE-7,SYS_CREATION_DATE= SYSDATE-7
WHERE UR_NUMBER = 'UR170200184';

DELETE FROM ASRM_PARPACT_REPORT_STS 
WHERE UR_NUMBER = 'UR170700833';

-- mew
SELECT *
FROM ASRM_PAIR_TRACKING 
--WHERE UR_NO = 'UR160501308'
ORDER BY TRUNC(PAIR_REQUEST_DATE) DESC


SELECT SYS_CREATION_DATE,MAX(UR_NUMBER) AS UR
FROM ASRM_PARPACT_REPORT_STS 
--WHERE ROWNUM < 2
WHERE TRUNC(SYS_CREATION_DATE) > TRUNC(SYSDATE-20)
GROUP BY SYS_CREATION_DATE
ORDER BY TRUNC(SYS_CREATION_DATE) DESC
