
SELECT * FROM RM1_CATEGORY_ASSIGNMENTS -- 6

SELECT * FROM RM1_END_STATUS -- 5

SELECT * FROM RM_ACTIVITY_PARAMS -- 10

SELECT * FROM RM_CATEGORY_ATTR -- 3

SELECT * FROM RM_CATEGORY_ATTR_VAL -- 18

SELECT * FROM RM_CATEGORY_RULES -- 259

SELECT * FROM RM_CATEGORY_VALUES -- 6

SELECT * FROM RM_DEPEND_ATTR -- 12

SELECT * FROM RM_DICTIONARY -- 66

SELECT * FROM RM_ITEM_DEFINITION -- 0

SELECT * FROM RM_LIFE_CYCLE -- 6

SELECT * FROM RM_LIFE_CYCLE_ACT -- 149

SELECT * FROM RM_MANUFACTURER -- 0

SELECT * FROM RM_OPERATOR_VARS -- 0

SELECT * FROM RM_PACKAGE_CMP_ACTV -- 70

SELECT * FROM RM_PACKAGE_CMP_STS -- 6

SELECT * FROM RM_PACKAGE_LIFE_CYC -- 2

SELECT * FROM RM_PACKAGE_TP_ATTR -- 19

SELECT * FROM RM_PACKAGE_TYPE -- 2

SELECT * FROM RM_PACKAGE_TYPE_CONT -- 4

SELECT * FROM RM_PARAM_PROPERTY -- 5

SELECT * FROM RM_PARAM_TYPE -- 2

SELECT * FROM RM_POLICY -- 0

SELECT * FROM RM_RESOURCE_LIFE_CYC -- 4

SELECT * FROM RM_RESOURCE_POOL_ATR -- 5

SELECT * FROM RM_RESOURCE_TP_ATTR -- 36

SELECT * FROM RM_RESOURCE_TP_CAT -- 1

SELECT * FROM RM_RESOURCE_TYPE -- 4

SELECT * FROM RM_RULE_PROPERTY -- 5

SELECT * FROM RM_RULE_TYPE -- 5

SELECT * FROM RM_SERIAL_TYPE -- 0

SELECT * FROM RM_TREATMENT_POLICY -- 0

SELECT * FROM RM_VENDOR -- 0

SELECT * FROM URM1_FLOW_CUSTOMIZE -- 0

SELECT * FROM URM1_NOTIFICATION_MODES -- 0

SELECT * FROM URM1_REF_SEQUENCES -- 28

SELECT * FROM URM1_SERVICES -- 0

SELECT * FROM URM1_THRESHOLDS -- 0

SELECT * FROM URM1_THRESHOLD_CRITERIA -- 0

SELECT * FROM URM9_CST_GEN_PARAMS -- 261

SELECT * FROM URM9_NATIONAL_NDC -- 4169

