SELECT TRUNC(PAIR_PREACT_DATE) PAIR_DATE, AMOUNT, FIRST_SIM, LAST_SIM 
FROM ASRM_PARPACT_REPORT_STS 
WHERE TRUNC(PAIR_PREACT_DATE) = TRUNC(SYSDATE) 

SELECT * FROM ASRM_PARPACT_REPORT_STS 
WHERE UR_NUMBER = 'UR161002029' 
AND TRUNC(PAIR_PREACT_DATE) = TRUNC(SYSDATE)

DELETE FROM ASRM_PARPACT_REPORT_STS  
WHERE TRUNC(PAIR_PREACT_DATE) = TRUNC(SYSDATE) 
AND UR_NUMBER = 'UR161002029'

