-- ASRM_RESERVE_LOGFILE
SELECT * 
FROM ASRM_RESERVE_LOGFILE 
WHERE msisdn IN (
'0863940392'
);


SELECT TRUNC(RESERVED_DATE) RESERVED_DATE,COUNT(1) amount,REMARK
FROM ASRM_RESERVE_LOGFILE 
GROUP BY RESERVED_DATE,REMARK 
ORDER BY RESERVED_DATE DESC;

--##################################################

DELETE FROM ASRM_RESERVE_LOGFILE 
WHERE ERROR_CASE IN ('2');

DELETE FROM ASRM_RESERVE_LOGFILE 
WHERE MSISDN IN ('0954685488');

INSERT INTO ASRM_RESERVE_LOGFILE 
(RESERVED_DATE, MSISDN, ERROR_CASE, REMARK)
VALUES
(TO_DATE(SYSDATE,'DD-MM-YY'),'0898788240','1','')

CREATE TABLE ASRM_RESERVE_LOGFILE
(
Reserved_Date DATE,
MSISDN VARCHAR(50),
Error_Case VARCHAR(50),
REMARK VARCHAR(100)
)

DROP TABLE ASRM_RESERVE_LOGFILE
