UPDATE rm1_resource SET 
RESOURCE_POOL_ID = '181'
WHERE resource_value = '0891001331'
AND RESOURCE_POOL_ID = '1'
AND resource_status = 'ACTIVE'

SELECT n.SYS_UPDATE_DATE,RESOURCE_VALUE,RESOURCE_STATUS,RRP_POOL_DESC,rma.RCAS_CATEGORY_VALUE,LAST_ACTIVITY_NAME,RRP_ID,LAST_ACTIVITY_DATE,n.RESOURCE_PARENT_VALUE
FROM rm1_resource n,PRDREFSSC.rm_resource_pool p ,RM1_CATEGORY_ASSIGNMENTS rma
WHERE n.resource_value IN (
'0891001331'
) AND RESOURCE_POOL_ID = rrp_id(+)
AND n.CATEGORY_INDEX = rma.RCAS_INDEX

UPDATE rm1_resource_history SET 
RESOURCE_POOL_ID = '181'
WHERE resource_value = '0891001331' 
AND resource_status = 'ACTIVE'
AND RESOURCE_POOL_ID = '1'
AND TRUNC(LAST_ACTIVITY_DATE) = TO_DATE('15/11/2016','dd/mm/yyyy')

SELECT RESOURCE_VALUE, RESOURCE_POOL_ID, RESOURCE_STATUS, LAST_ACTIVITY_NAME, LAST_ACTIVITY_DATE, RESOURCE_PARENT_VALUE 
FROM rm1_resource_history
WHERE resource_value = '0891001331' 
ORDER BY LAST_ACTIVITY_DATE DESC


-- up pool
UPDATE rm1_resource SET 
RESOURCE_POOL_ID = '153'
WHERE resource_value = '0963702007'
AND RESOURCE_POOL_ID = '82'
AND resource_status = 'ACTIVE'

SELECT n.SYS_UPDATE_DATE,RESOURCE_VALUE,RESOURCE_STATUS,RRP_POOL_DESC,rma.RCAS_CATEGORY_VALUE,LAST_ACTIVITY_NAME,RRP_ID,LAST_ACTIVITY_DATE,n.RESOURCE_PARENT_VALUE
FROM rm1_resource n,PRDREFSSC.rm_resource_pool p ,RM1_CATEGORY_ASSIGNMENTS rma
WHERE n.resource_value IN (
'0963702007'
) AND RESOURCE_POOL_ID = rrp_id(+)
AND n.CATEGORY_INDEX = rma.RCAS_INDEX

UPDATE rm1_resource_history SET 
RESOURCE_POOL_ID = '153'
WHERE resource_value = '0963702007' 
AND resource_status = 'ACTIVE'
AND RESOURCE_POOL_ID = '82'
AND TRUNC(LAST_ACTIVITY_DATE) = TO_DATE('10/11/2016','dd/mm/yyyy')

SELECT RESOURCE_VALUE, RESOURCE_POOL_ID, RESOURCE_STATUS, LAST_ACTIVITY_NAME, LAST_ACTIVITY_DATE, RESOURCE_PARENT_VALUE 
FROM rm1_resource_history
WHERE resource_value = '0963702007' 
ORDER BY LAST_ACTIVITY_DATE DESC

----------------------------
UPDATE rm1_resource_attributes SET resource_attr_value = 'Y' 
WHERE resource_value_id IN (SELECT resource_id FROM rm1_resource WHERE resource_value = '0891001331')
AND resource_attribute_id = 1

SELECT n.SYS_UPDATE_DATE,RESOURCE_VALUE,RESOURCE_STATUS,LAST_ACTIVITY_NAME,LAST_ACTIVITY_DATE,RRP_ID,RRP_POOL_DESC,
rma.RCAS_CATEGORY_VALUE ,rrta.rtat_attr_name,rra.resource_attr_value,n.LAST_ACTIVITY_ISSUE_DATE
--DECODE(rra.resource_attr_value,'1','BK', '2','UE','3','LE','4','UN','5','LN','6','US','7','LS') ngp
FROM rm1_resource n,rm_resource_pool p ,RM1_CATEGORY_ASSIGNMENTS rma ,RM1_RESOURCE_ATTRIBUTES rra,RM_RESOURCE_TP_ATTR rrta
WHERE n.resource_value = '0891001331'
AND RESOURCE_POOL_ID = rrp_id(+)
AND rra.resource_attribute_id = rrta.rtat_id(+)
AND n.CATEGORY_INDEX = rma.RCAS_INDEX
AND n.RESOURCE_ID = rra.RESOURCE_VALUE_ID